"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ensureDir = exports.resolveConflict = exports.preallocate = exports.verifyChecksum = exports.computeChecksum = exports.SpeedLimiter = exports.sleep = exports.withRetry = exports.isMagnetUri = exports.parseMagnetUri = exports.FtpProtocol = exports.HttpProtocol = exports.ResumeManager = exports.ProgressTracker = exports.ChunkAllocator = exports.SegmentManager = exports.DownloadManager = void 0;
var downloadManager_1 = require("./core/downloadManager");
Object.defineProperty(exports, "DownloadManager", { enumerable: true, get: function () { return downloadManager_1.DownloadManager; } });
var segmentManager_1 = require("./core/segmentManager");
Object.defineProperty(exports, "SegmentManager", { enumerable: true, get: function () { return segmentManager_1.SegmentManager; } });
var chunkAllocator_1 = require("./core/chunkAllocator");
Object.defineProperty(exports, "ChunkAllocator", { enumerable: true, get: function () { return chunkAllocator_1.ChunkAllocator; } });
var progressTracker_1 = require("./core/progressTracker");
Object.defineProperty(exports, "ProgressTracker", { enumerable: true, get: function () { return progressTracker_1.ProgressTracker; } });
var resumeManager_1 = require("./core/resumeManager");
Object.defineProperty(exports, "ResumeManager", { enumerable: true, get: function () { return resumeManager_1.ResumeManager; } });
var http_1 = require("./protocols/http");
Object.defineProperty(exports, "HttpProtocol", { enumerable: true, get: function () { return http_1.HttpProtocol; } });
var ftp_1 = require("./protocols/ftp");
Object.defineProperty(exports, "FtpProtocol", { enumerable: true, get: function () { return ftp_1.FtpProtocol; } });
var magnet_1 = require("./protocols/magnet");
Object.defineProperty(exports, "parseMagnetUri", { enumerable: true, get: function () { return magnet_1.parseMagnetUri; } });
Object.defineProperty(exports, "isMagnetUri", { enumerable: true, get: function () { return magnet_1.isMagnetUri; } });
var retry_1 = require("./utils/retry");
Object.defineProperty(exports, "withRetry", { enumerable: true, get: function () { return retry_1.withRetry; } });
Object.defineProperty(exports, "sleep", { enumerable: true, get: function () { return retry_1.sleep; } });
var speedLimiter_1 = require("./utils/speedLimiter");
Object.defineProperty(exports, "SpeedLimiter", { enumerable: true, get: function () { return speedLimiter_1.SpeedLimiter; } });
var checksum_1 = require("./utils/checksum");
Object.defineProperty(exports, "computeChecksum", { enumerable: true, get: function () { return checksum_1.computeChecksum; } });
Object.defineProperty(exports, "verifyChecksum", { enumerable: true, get: function () { return checksum_1.verifyChecksum; } });
var fileWriter_1 = require("./utils/fileWriter");
Object.defineProperty(exports, "preallocate", { enumerable: true, get: function () { return fileWriter_1.preallocate; } });
Object.defineProperty(exports, "resolveConflict", { enumerable: true, get: function () { return fileWriter_1.resolveConflict; } });
Object.defineProperty(exports, "ensureDir", { enumerable: true, get: function () { return fileWriter_1.ensureDir; } });
