export declare const DEFAULT_MAX_CONNECTIONS = 8;
export declare const DEFAULT_CHUNK_SIZE: number;
export declare const DEFAULT_CONCURRENT_DOWNLOADS = 3;
export declare const DEFAULT_RETRY_COUNT = 5;
export declare const DEFAULT_RETRY_DELAY = 3000;
export declare const DEFAULT_CONNECTION_TIMEOUT = 30000;
export declare const EXTENSION_PORT = 9182;
export declare const MERGE_BUFFER_SIZE: number;
export declare const PROGRESS_UPDATE_INTERVAL = 500;
export declare const CATEGORY_EXTENSIONS: Record<string, string[]>;
export declare const IPC_CHANNELS: {
    readonly DOWNLOAD_ADD: "download:add";
    readonly DOWNLOAD_PAUSE: "download:pause";
    readonly DOWNLOAD_RESUME: "download:resume";
    readonly DOWNLOAD_CANCEL: "download:cancel";
    readonly DOWNLOAD_REMOVE: "download:remove";
    readonly DOWNLOAD_PROGRESS: "download:progress";
    readonly DOWNLOAD_LIST: "download:list";
    readonly DOWNLOAD_OPEN: "download:open";
    readonly DOWNLOAD_OPEN_DIR: "download:open-dir";
    readonly QUEUE_LIST: "queue:list";
    readonly QUEUE_CREATE: "queue:create";
    readonly QUEUE_UPDATE: "queue:update";
    readonly QUEUE_DELETE: "queue:delete";
    readonly QUEUE_START: "queue:start";
    readonly QUEUE_STOP: "queue:stop";
    readonly QUEUE_STATS: "queue:stats";
    readonly SCHEDULER_LIST: "scheduler:list";
    readonly SCHEDULER_CREATE: "scheduler:create";
    readonly SCHEDULER_UPDATE: "scheduler:update";
    readonly SCHEDULER_DELETE: "scheduler:delete";
    readonly SCHEDULER_TOGGLE: "scheduler:toggle";
    readonly SETTINGS_GET: "settings:get";
    readonly SETTINGS_SET: "settings:set";
    readonly SETTINGS_RESET: "settings:reset";
    readonly DIALOG_OPEN_DIR: "dialog:open-dir";
    readonly DIALOG_SAVE_FILE: "dialog:save-file";
    readonly SHELL_OPEN: "shell:open";
    readonly APP_MINIMIZE: "app:minimize";
    readonly APP_QUIT: "app:quit";
    readonly UPDATER_CHECK: "updater:check";
};
//# sourceMappingURL=constants.d.ts.map